### ISSUE TITLE
Change the UI for sidebar counters with too many items

### ISSUE THREAD

**Issue by reekitconcept** [kitconcept/volto-solr#23]
Sidebar counters that have >99 hits, currently show "...". We want to change this, but we need to decide how. The problem is that long numbers with 4 or 5 digits, for example 1111, 11111, etc. are typical but they cannot be displayed in the current way because the number would be too small.

Solution:

- We need 3 digits, make flatter badge
- everything above 999: show 1K etc.
- everything about 99K: 99K and that's it....

**Comment by steffenri** [comment]
# Screenshot

![Search (12)](https://github.com/kitconcept/volto-solr/assets/54619639/22959704-f5a7-4bfa-bde3-807b116ec159)

**Comment by steffenri** [comment]
## Screenshot

![Search (13)](https://github.com/kitconcept/volto-solr/assets/54619639/b1d028a2-173b-4195-aedc-b4253f8dd4ca)
